package de.tudarmstadt.ukp.exploration.graph_doc_explorer.webapp.application.search;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.LinkedList;
import java.util.List;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import de.tudarmstadt.ukp.exploration.graph_doc_explorer.graphs.SearchResult;

/**
 * Use the locally installed Solr server to search the document stock
 * 
 * @author Alexander Goessl, Arwed Goelz
 */
public class SolrSearchHTTP implements ISearcher {

	private String solrURI = "http://localhost:8983/solr/documents/select?";
	private String format = "json";

	/**
	 * Wraps actual class functionality to be used via the ISearcher interface
	 * 
	 * @param keyword
	 *            the keyword to query Solr with
	 * @return The complete list of all documents containing the phrase searched
	 *         for
	 */
	@Override
	public List<SearchResult> query(String keyword, String groupID) {
		try {
			return this.parseJSONResults(this.sendHTTPQuerytoSolr(keyword));
		} catch (IOException e) {
			e.printStackTrace();
		}
		return null;
	}

	/**
	 * Query the Solr server with the keyword
	 * 
	 * @param keyword
	 *            the keyword to query Solr with
	 * @return JSON response from Solr containing the raw search results
	 * @throws IOException
	 */
	private String sendHTTPQuerytoSolr(String keyword) throws IOException {

		String urlString = this.solrURI + "q=" + URLEncoder.encode(keyword, "UTF-8") + "&wt=" + this.format;

		URL requestURL = new URL(urlString);
		URLConnection requestConnection = requestURL.openConnection();
		BufferedReader in = new BufferedReader(
				new InputStreamReader(requestConnection.getInputStream(), StandardCharsets.UTF_8));

		String searchResults = in.readLine();
		in.close();

		return searchResults;
	}

	/**
	 * Parse JSON results generated by Solr, extract path(s) to file(s)
	 * 
	 * @param searchResultsJSON
	 *            The query as generated by sendHTTPQuerytoSolr()
	 * @return The search results as a list
	 */
	private List<SearchResult> parseJSONResults(String searchResultsJSON) {

		List<SearchResult> searchResults = new LinkedList<SearchResult>();

		JsonElement rootElement = new JsonParser().parse(searchResultsJSON);
		JsonObject rootObject = rootElement.getAsJsonObject();
		JsonObject responseObject = rootObject.getAsJsonObject("response");
		JsonArray docsArray = responseObject.getAsJsonArray("docs");
		for (JsonElement resultElement : docsArray) {
			JsonObject resultObject = resultElement.getAsJsonObject();
			String pathToResource = resultObject.getAsJsonArray("resourcename").getAsString();

			// Use the whole filename as ID... webapp seems to expect full
			// filename to load file
			String id = pathToResource.substring(pathToResource.lastIndexOf("/") + 1);

			String[] doc = this.readFile(pathToResource);

			searchResults.add(new SearchResult(id, doc[0], doc[1]));
		}

		return searchResults;
	}

	/**
	 * Reads a file and returns a String array, of which the first element
	 * contains the first line of the file and the second element contains the
	 * whole text.
	 * 
	 * @param path
	 *            The path where the file is located
	 * @return A String array consisting of two fields, where the first field
	 *         contains the first line of the given file and the second field
	 *         contains the whole file.
	 */
	private String[] readFile(String path) {

		File file = new File(path);

		try {
			InputStreamReader reader = new InputStreamReader(new FileInputStream(file), StandardCharsets.UTF_8);
			BufferedReader bufferedReader = new BufferedReader(reader);

			String title = bufferedReader.readLine();
			String line = title;

			while (bufferedReader.ready()) {
				line += bufferedReader.readLine() + " ";
			}
			bufferedReader.close();
			reader.close();

			return new String[] { title, line };

		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}

		return new String[] { "404 Not Found", "404 Not Found" };
	}

	@Override
	public List<String> groupIDs() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setUrl(String url) {
		// TODO Auto-generated method stub

	}

}