package de.tudarmstadt.ukp.exploration.graph_doc_explorer.graphs;

import java.util.List;

/**
 * The interface which all graph generators have to implement.
 */
public interface IGraphGenerator {

	/**
	 * Initializes the graph generator. The initialization needs the search
	 * results to construct the graph. The folder where the corresponding
	 * documents are located is useful as it allows storing additional
	 * information for the graph generator in the folder.
	 * 
	 * @param searchResults
	 *            A list containing all search results.
	 * @param folder
	 *            The folder containing the files for this document collection.
	 */
	public void initialize(List<SearchResult> searchResults, String folder, String[] args);

	/**
	 * Add a User Action to the graph generator. The User Action is modeled by a
	 * LogEntry which contains more information than just the action itself.
	 * 
	 * @param userAction
	 *            A LogEntry corresponding to a user action. The LogEntry
	 *            contains more information than just the user action. For
	 *            example the user action "node centered" is always logged
	 *            together with the nodes which are visible after centering the
	 *            node.
	 */
	public void addUserAction(LogEntry userAction);

	/**
	 * Returns the graph generated by the graph generator.
	 * 
	 * @return The graph object containing all the graph's nodes and edges.
	 */
	public Graph getGraph();

}
